// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcCuIk9oAnhVZrjWwz9_CeNURjAnvXaXI',
    appId: '1:512330142881:web:29c27ef33f2e81e05f0ce0',
    messagingSenderId: '512330142881',
    projectId: 'wedding-rsvp-c0b47',
    authDomain: 'wedding-rsvp-c0b47.firebaseapp.com',
    storageBucket: 'wedding-rsvp-c0b47.firebasestorage.app',
    measurementId: 'G-SJ272F25TM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQGEh-swcXRdRMm4l8-5sd67uT2AGziB0',
    appId: '1:512330142881:android:de5a5e237568b8055f0ce0',
    messagingSenderId: '512330142881',
    projectId: 'wedding-rsvp-c0b47',
    storageBucket: 'wedding-rsvp-c0b47.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2ciWiFujeWS_Z8hIhcCrD9iRfIAgvgZM',
    appId: '1:512330142881:ios:ee47c53adbd7845a5f0ce0',
    messagingSenderId: '512330142881',
    projectId: 'wedding-rsvp-c0b47',
    storageBucket: 'wedding-rsvp-c0b47.firebasestorage.app',
    iosBundleId: 'com.example.weddingRsvp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2ciWiFujeWS_Z8hIhcCrD9iRfIAgvgZM',
    appId: '1:512330142881:ios:ee47c53adbd7845a5f0ce0',
    messagingSenderId: '512330142881',
    projectId: 'wedding-rsvp-c0b47',
    storageBucket: 'wedding-rsvp-c0b47.firebasestorage.app',
    iosBundleId: 'com.example.weddingRsvp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcCuIk9oAnhVZrjWwz9_CeNURjAnvXaXI',
    appId: '1:512330142881:web:f09db9e338c60fca5f0ce0',
    messagingSenderId: '512330142881',
    projectId: 'wedding-rsvp-c0b47',
    authDomain: 'wedding-rsvp-c0b47.firebaseapp.com',
    storageBucket: 'wedding-rsvp-c0b47.firebasestorage.app',
    measurementId: 'G-YSH8KJ38K1',
  );
}
